---

- name: Update cache
  apt:
    update_cache: true

# This is required because it provides the /bin/kill binary used in the service file
- name: Install procps
  apt:
    name: procps
    state: present

- name: Install libcap
  apt:
    name: libcap2-bin
    state: present
  when: caddy_setcap
